service:
  name: 'sls-example'

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude: ['aws-sdk']
    target: node14
    define: { 'require.resolve': undefined }
    platform: node

plugins:
  - 'serverless-esbuild'
  - 'serverless-offline'

provider:
  name: aws
  runtime: nodejs14.x
  profile: my-app-user
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
    shouldStartNameWithService: true
  environment:
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
  lambdaHashingVersion: '20201221'

functions:
  hello:
    handler: src/controllers/helloController.hello
    events:
      - http:
          method: get
          path: api/hello